#define DITHER_MODE_DISABLED 0xff
#define DITHER_MODE_PER_PIXEL_2X2 0
#define DITHER_MODE_PER_PIXEL_3X3 1
#define DITHER_MODE_PER_PIXEL_4X4 2
#define DITHER_MODE_RUSSIAN_ROULETTE 4
#define DITHER_MODE_DITHER_TEMPORAL_AA 10
#define DITHER_MODE_STBN 11

#define OBJECT_HASH_QUADS 0
#define OBJECT_HASH_GEOMETRY 0

#ifndef DITHER_MODE
#define DITHER_MODE DITHER_MODE_RUSSIAN_ROULETTE
#endif

#define COVERAGE_CORRECTION_DISABLED 0
#define COVERAGE_CORRECTION_DLSS 1
#define COVERAGE_CORRECTION_FSR 2
#define COVERAGE_CORRECTION_XESS 3

#ifndef COVERAGE_CORRECTION
#define COVERAGE_CORRECTION COVERAGE_CORRECTION_DISABLED
#endif

Texture2D<float> gBlueNoise64x64Tex;
Texture2DArray<float> gSpatioTemporalBlueNoiseTex;
StructuredBuffer<uint> gPermutations3x3; // permutations packed into 4 bytes

cbuffer DitherConstants
{
    int gRotatePattern;
    uint gObjectHashType;
    uint gDitherTAAPermutations; // enables permutations for dither taa
};

// common variables used in the dithering functions
struct DitherInfo
{
    uint2 pixel;
    uint frameIndex; // usually for per frame rng
    float3 posW; // world position (for white noise)
};

static const int4x4 ditherMatrix = int4x4(
        int4(0, 8, 2, 10),
        int4(12, 4, 14, 6),
        int4(3, 11, 1, 9),
        int4(15, 7, 13, 5)
    );

float getObjectHash();

uint3x3 get3x3Permutation(uint id)
{
    uint elementCount, stride;
    gPermutations3x3.GetDimensions(elementCount, stride);
    uint packed = gPermutations3x3[id % elementCount];
    uint3x3 m;
    uint sumValues = 0; // To track the sum of the extracted values

    // Extract the first 8 values (4 bits each)
    [unroll] for (int i = 0; i < 8; i++)
    {
        uint value = (packed >> (i * 4)) & 0xF;
        m[i / 3][i % 3] = value;
        sumValues += value;
    }

    // Compute the missing value using sum formula (0+1+2+3+4+5+6+7+8 = 36)
    m[2][2] = 36 - sumValues;

    return m;
}

uint4 get2x2Permutation(uint i) {
    switch (i % 24u) {
        case 0:  return uint4(0, 1, 2, 3);
        case 1:  return uint4(0, 1, 3, 2);
        case 2:  return uint4(0, 2, 1, 3);
        case 3:  return uint4(0, 2, 3, 1);
        case 4:  return uint4(0, 3, 1, 2);
        case 5:  return uint4(0, 3, 2, 1);
        case 6:  return uint4(1, 0, 2, 3);
        case 7:  return uint4(1, 0, 3, 2);
        case 8:  return uint4(1, 2, 0, 3);
        case 9:  return uint4(1, 2, 3, 0);
        case 10: return uint4(1, 3, 0, 2);
        case 11: return uint4(1, 3, 2, 0);
        case 12: return uint4(2, 0, 1, 3);
        case 13: return uint4(2, 0, 3, 1);
        case 14: return uint4(2, 1, 0, 3);
        case 15: return uint4(2, 1, 3, 0);
        case 16: return uint4(2, 3, 0, 1);
        case 17: return uint4(2, 3, 1, 0);
        case 18: return uint4(3, 0, 1, 2);
        case 19: return uint4(3, 0, 2, 1);
        case 20: return uint4(3, 1, 0, 2);
        case 21: return uint4(3, 1, 2, 0);
        case 22: return uint4(3, 2, 0, 1);
        case 23: return uint4(3, 2, 1, 0);
        default: return 0u;
    }
}

uint4 get2x2PrettyPermutation(uint i) {
    // only pretty configurations (first two numbers form a diagonal)
    switch (i % 8u) {
        case 0:  return uint4(0, 2, 3, 1);
        case 1:  return uint4(0, 3, 2, 1);
        case 2:  return uint4(2, 0, 1, 3);
        case 3:  return uint4(3, 0, 1, 2);
        case 4:  return uint4(2, 1, 0, 3);
        case 5:  return uint4(3, 1, 0, 2);
        case 6:  return uint4(1, 2, 3, 0);
        case 7:  return uint4(1, 3, 2, 0);
        default: return 0u;
    }
}


float hash1D(float v)
{
    return frac(1.0e4 * sin(17.0 * v.x) * (0.1 + abs(sin(v.x))));
}

// Hash function from "Improved Alpha Testing Using Hashed Sampling"
float hash(float2 v)
{
    return frac(1.0e4 * sin(17.0 * v.x + 0.1 * v.y) * (0.1 + abs(sin(13.0 * v.y + v.x))));
}

// 3D hash function from "Improved Alpha Testing Using Hashed Sampling"
float hash3D(float3 v)
{
    return hash(float2(hash(v.xy), v.z));
}

// 4D hash function based on the 3D hash function
float hash4D(float4 v)
{
    //return hash(float2(hash3D(v.xyz), v.w));
    return hash(float2(hash(v.xy), hash(v.zw)));
}

float getTopNoise(DitherInfo d)
{
    return gBlueNoise64x64Tex[d.pixel % 64u];
}

float getRouletteThreshold(DitherInfo d)
{
    float rng = hash4D(float4(d.posW, d.frameIndex));
    return rng;
}

uint2 applyRotation(uint2 pixel, uint offset, uint width, uint height)
{
    uint xoff = offset % width;
    uint yoff = (offset / width);
    if (yoff % 2u) xoff = width - xoff - 1; // serpentine raster
    pixel.x += xoff;
    pixel.y += yoff;
    return pixel;
}

float getPixelDitherThreshold2x2(DitherInfo d)
{
    // use random offset to ensure that each primitive uses a different mask
    uint randomOffset = uint(getObjectHash() * 7919);

    uint4 mask = get2x2Permutation(randomOffset); // mask with [0, 1, 2, 3] permutation
    uint2 p = d.pixel;
    if (gRotatePattern)
        p = applyRotation(p, d.frameIndex, 2, 2); // rotate lookup based on frame index
    uint lookup = (p.x % 2u) + 2u * (p.y % 2u);
    uint v = mask[lookup]; // 0, 1, 2 or 3

    return (v + getTopNoise(d)) / 4.0;
}

float getPixelDitherThreshold3x3(DitherInfo d)
{
    // use random offset to ensure that each primitive uses a different mask
    uint randomOffset = uint(getObjectHash() * 7919);
    uint2 p = d.pixel;
    if(gRotatePattern)
        p = applyRotation(p, d.frameIndex, 3, 3);
    
    p = p % 3u;

    uint3x3 mask = get3x3Permutation(randomOffset);
    uint v = mask[p.y][p.x]; // 0-8

    return (v + getTopNoise(d)) / 9.0;
}



// Hardcoded version of the i-th permutation of [0,1,2,3,4].
void GetPermutation5(uint i, out int result[5])
{
    switch(i % 120u)
    {
        case 0:  result[0]=0; result[1]=1; result[2]=2; result[3]=3; result[4]=4; break;
        case 1:  result[0]=0; result[1]=1; result[2]=2; result[3]=4; result[4]=3; break;
        case 2:  result[0]=0; result[1]=1; result[2]=3; result[3]=2; result[4]=4; break;
        case 3:  result[0]=0; result[1]=1; result[2]=3; result[3]=4; result[4]=2; break;
        case 4:  result[0]=0; result[1]=1; result[2]=4; result[3]=2; result[4]=3; break;
        case 5:  result[0]=0; result[1]=1; result[2]=4; result[3]=3; result[4]=2; break;
        case 6:  result[0]=0; result[1]=2; result[2]=1; result[3]=3; result[4]=4; break;
        case 7:  result[0]=0; result[1]=2; result[2]=1; result[3]=4; result[4]=3; break;
        case 8:  result[0]=0; result[1]=2; result[2]=3; result[3]=1; result[4]=4; break;
        case 9:  result[0]=0; result[1]=2; result[2]=3; result[3]=4; result[4]=1; break;
        case 10: result[0]=0; result[1]=2; result[2]=4; result[3]=1; result[4]=3; break;
        case 11: result[0]=0; result[1]=2; result[2]=4; result[3]=3; result[4]=1; break;
        case 12: result[0]=0; result[1]=3; result[2]=1; result[3]=2; result[4]=4; break;
        case 13: result[0]=0; result[1]=3; result[2]=1; result[3]=4; result[4]=2; break;
        case 14: result[0]=0; result[1]=3; result[2]=2; result[3]=1; result[4]=4; break;
        case 15: result[0]=0; result[1]=3; result[2]=2; result[3]=4; result[4]=1; break;
        case 16: result[0]=0; result[1]=3; result[2]=4; result[3]=1; result[4]=2; break;
        case 17: result[0]=0; result[1]=3; result[2]=4; result[3]=2; result[4]=1; break;
        case 18: result[0]=0; result[1]=4; result[2]=1; result[3]=2; result[4]=3; break;
        case 19: result[0]=0; result[1]=4; result[2]=1; result[3]=3; result[4]=2; break;
        case 20: result[0]=0; result[1]=4; result[2]=2; result[3]=1; result[4]=3; break;
        case 21: result[0]=0; result[1]=4; result[2]=2; result[3]=3; result[4]=1; break;
        case 22: result[0]=0; result[1]=4; result[2]=3; result[3]=1; result[4]=2; break;
        case 23: result[0]=0; result[1]=4; result[2]=3; result[3]=2; result[4]=1; break;

        case 24: result[0]=1; result[1]=0; result[2]=2; result[3]=3; result[4]=4; break;
        case 25: result[0]=1; result[1]=0; result[2]=2; result[3]=4; result[4]=3; break;
        case 26: result[0]=1; result[1]=0; result[2]=3; result[3]=2; result[4]=4; break;
        case 27: result[0]=1; result[1]=0; result[2]=3; result[3]=4; result[4]=2; break;
        case 28: result[0]=1; result[1]=0; result[2]=4; result[3]=2; result[4]=3; break;
        case 29: result[0]=1; result[1]=0; result[2]=4; result[3]=3; result[4]=2; break;
        case 30: result[0]=1; result[1]=2; result[2]=0; result[3]=3; result[4]=4; break;
        case 31: result[0]=1; result[1]=2; result[2]=0; result[3]=4; result[4]=3; break;
        case 32: result[0]=1; result[1]=2; result[2]=3; result[3]=0; result[4]=4; break;
        case 33: result[0]=1; result[1]=2; result[2]=3; result[3]=4; result[4]=0; break;
        case 34: result[0]=1; result[1]=2; result[2]=4; result[3]=0; result[4]=3; break;
        case 35: result[0]=1; result[1]=2; result[2]=4; result[3]=3; result[4]=0; break;
        case 36: result[0]=1; result[1]=3; result[2]=0; result[3]=2; result[4]=4; break;
        case 37: result[0]=1; result[1]=3; result[2]=0; result[3]=4; result[4]=2; break;
        case 38: result[0]=1; result[1]=3; result[2]=2; result[3]=0; result[4]=4; break;
        case 39: result[0]=1; result[1]=3; result[2]=2; result[3]=4; result[4]=0; break;
        case 40: result[0]=1; result[1]=3; result[2]=4; result[3]=0; result[4]=2; break;
        case 41: result[0]=1; result[1]=3; result[2]=4; result[3]=2; result[4]=0; break;
        case 42: result[0]=1; result[1]=4; result[2]=0; result[3]=2; result[4]=3; break;
        case 43: result[0]=1; result[1]=4; result[2]=0; result[3]=3; result[4]=2; break;
        case 44: result[0]=1; result[1]=4; result[2]=2; result[3]=0; result[4]=3; break;
        case 45: result[0]=1; result[1]=4; result[2]=2; result[3]=3; result[4]=0; break;
        case 46: result[0]=1; result[1]=4; result[2]=3; result[3]=0; result[4]=2; break;
        case 47: result[0]=1; result[1]=4; result[2]=3; result[3]=2; result[4]=0; break;

        case 48: result[0]=2; result[1]=0; result[2]=1; result[3]=3; result[4]=4; break;
        case 49: result[0]=2; result[1]=0; result[2]=1; result[3]=4; result[4]=3; break;
        case 50: result[0]=2; result[1]=0; result[2]=3; result[3]=1; result[4]=4; break;
        case 51: result[0]=2; result[1]=0; result[2]=3; result[3]=4; result[4]=1; break;
        case 52: result[0]=2; result[1]=0; result[2]=4; result[3]=1; result[4]=3; break;
        case 53: result[0]=2; result[1]=0; result[2]=4; result[3]=3; result[4]=1; break;
        case 54: result[0]=2; result[1]=1; result[2]=0; result[3]=3; result[4]=4; break;
        case 55: result[0]=2; result[1]=1; result[2]=0; result[3]=4; result[4]=3; break;
        case 56: result[0]=2; result[1]=1; result[2]=3; result[3]=0; result[4]=4; break;
        case 57: result[0]=2; result[1]=1; result[2]=3; result[3]=4; result[4]=0; break;
        case 58: result[0]=2; result[1]=1; result[2]=4; result[3]=0; result[4]=3; break;
        case 59: result[0]=2; result[1]=1; result[2]=4; result[3]=3; result[4]=0; break;
        case 60: result[0]=2; result[1]=3; result[2]=0; result[3]=1; result[4]=4; break;
        case 61: result[0]=2; result[1]=3; result[2]=0; result[3]=4; result[4]=1; break;
        case 62: result[0]=2; result[1]=3; result[2]=1; result[3]=0; result[4]=4; break;
        case 63: result[0]=2; result[1]=3; result[2]=1; result[3]=4; result[4]=0; break;
        case 64: result[0]=2; result[1]=3; result[2]=4; result[3]=0; result[4]=1; break;
        case 65: result[0]=2; result[1]=3; result[2]=4; result[3]=1; result[4]=0; break;
        case 66: result[0]=2; result[1]=4; result[2]=0; result[3]=1; result[4]=3; break;
        case 67: result[0]=2; result[1]=4; result[2]=0; result[3]=3; result[4]=1; break;
        case 68: result[0]=2; result[1]=4; result[2]=1; result[3]=0; result[4]=3; break;
        case 69: result[0]=2; result[1]=4; result[2]=1; result[3]=3; result[4]=0; break;
        case 70: result[0]=2; result[1]=4; result[2]=3; result[3]=0; result[4]=1; break;
        case 71: result[0]=2; result[1]=4; result[2]=3; result[3]=1; result[4]=0; break;

        case 72: result[0]=3; result[1]=0; result[2]=1; result[3]=2; result[4]=4; break;
        case 73: result[0]=3; result[1]=0; result[2]=1; result[3]=4; result[4]=2; break;
        case 74: result[0]=3; result[1]=0; result[2]=2; result[3]=1; result[4]=4; break;
        case 75: result[0]=3; result[1]=0; result[2]=2; result[3]=4; result[4]=1; break;
        case 76: result[0]=3; result[1]=0; result[2]=4; result[3]=1; result[4]=2; break;
        case 77: result[0]=3; result[1]=0; result[2]=4; result[3]=2; result[4]=1; break;
        case 78: result[0]=3; result[1]=1; result[2]=0; result[3]=2; result[4]=4; break;
        case 79: result[0]=3; result[1]=1; result[2]=0; result[3]=4; result[4]=2; break;
        case 80: result[0]=3; result[1]=1; result[2]=2; result[3]=0; result[4]=4; break;
        case 81: result[0]=3; result[1]=1; result[2]=2; result[3]=4; result[4]=0; break;
        case 82: result[0]=3; result[1]=1; result[2]=4; result[3]=0; result[4]=2; break;
        case 83: result[0]=3; result[1]=1; result[2]=4; result[3]=2; result[4]=0; break;
        case 84: result[0]=3; result[1]=2; result[2]=0; result[3]=1; result[4]=4; break;
        case 85: result[0]=3; result[1]=2; result[2]=0; result[3]=4; result[4]=1; break;
        case 86: result[0]=3; result[1]=2; result[2]=1; result[3]=0; result[4]=4; break;
        case 87: result[0]=3; result[1]=2; result[2]=1; result[3]=4; result[4]=0; break;
        case 88: result[0]=3; result[1]=2; result[2]=4; result[3]=0; result[4]=1; break;
        case 89: result[0]=3; result[1]=2; result[2]=4; result[3]=1; result[4]=0; break;
        case 90: result[0]=3; result[1]=4; result[2]=0; result[3]=1; result[4]=2; break;
        case 91: result[0]=3; result[1]=4; result[2]=0; result[3]=2; result[4]=1; break;
        case 92: result[0]=3; result[1]=4; result[2]=1; result[3]=0; result[4]=2; break;
        case 93: result[0]=3; result[1]=4; result[2]=1; result[3]=2; result[4]=0; break;
        case 94: result[0]=3; result[1]=4; result[2]=2; result[3]=0; result[4]=1; break;
        case 95: result[0]=3; result[1]=4; result[2]=2; result[3]=1; result[4]=0; break;

        case 96:  result[0]=4; result[1]=0; result[2]=1; result[3]=2; result[4]=3; break;
        case 97:  result[0]=4; result[1]=0; result[2]=1; result[3]=3; result[4]=2; break;
        case 98:  result[0]=4; result[1]=0; result[2]=2; result[3]=1; result[4]=3; break;
        case 99:  result[0]=4; result[1]=0; result[2]=2; result[3]=3; result[4]=1; break;
        case 100: result[0]=4; result[1]=0; result[2]=3; result[3]=1; result[4]=2; break;
        case 101: result[0]=4; result[1]=0; result[2]=3; result[3]=2; result[4]=1; break;
        case 102: result[0]=4; result[1]=1; result[2]=0; result[3]=2; result[4]=3; break;
        case 103: result[0]=4; result[1]=1; result[2]=0; result[3]=3; result[4]=2; break;
        case 104: result[0]=4; result[1]=1; result[2]=2; result[3]=0; result[4]=3; break;
        case 105: result[0]=4; result[1]=1; result[2]=2; result[3]=3; result[4]=0; break;
        case 106: result[0]=4; result[1]=1; result[2]=3; result[3]=0; result[4]=2; break;
        case 107: result[0]=4; result[1]=1; result[2]=3; result[3]=2; result[4]=0; break;
        case 108: result[0]=4; result[1]=2; result[2]=0; result[3]=1; result[4]=3; break;
        case 109: result[0]=4; result[1]=2; result[2]=0; result[3]=3; result[4]=1; break;
        case 110: result[0]=4; result[1]=2; result[2]=1; result[3]=0; result[4]=3; break;
        case 111: result[0]=4; result[1]=2; result[2]=1; result[3]=3; result[4]=0; break;
        case 112: result[0]=4; result[1]=2; result[2]=3; result[3]=0; result[4]=1; break;
        case 113: result[0]=4; result[1]=2; result[2]=3; result[3]=1; result[4]=0; break;
        case 114: result[0]=4; result[1]=3; result[2]=0; result[3]=1; result[4]=2; break;
        case 115: result[0]=4; result[1]=3; result[2]=0; result[3]=2; result[4]=1; break;
        case 116: result[0]=4; result[1]=3; result[2]=1; result[3]=0; result[4]=2; break;
        case 117: result[0]=4; result[1]=3; result[2]=1; result[3]=2; result[4]=0; break;
        case 118: result[0]=4; result[1]=3; result[2]=2; result[3]=0; result[4]=1; break;
        case 119:
        default:  result[0]=4; result[1]=3; result[2]=2; result[3]=1; result[4]=0; break;
    }
}


// from unreal engine DitherTemporalAA
float ditherTemporalAAThreshold(DitherInfo d)
{
    // 5 translucency steps, high frequency regular pattern
    uint2 p = d.pixel + uint2(d.frameIndex);
    uint stratifyIndex = (p.x + p.y * 2u) % 5;

    
    if(gDitherTAAPermutations)
    {
        // Custom workaround to prevent different objects from masking each other out:
        int statifyNumbers[5]; // obtain one of the 120 permutations of [0, 1, 2, 3, 4]
        GetPermutation5(uint(getObjectHash() * 120), statifyNumbers);
        stratifyIndex = statifyNumbers[stratifyIndex];
    }

    // random noise to break up the 5 steps
    float blue = getTopNoise(d); // generalized with more noise types beside static blue
    //float t = (stratifyIndex + blue + rng) / 6.0; // original threshold, but biased
    float t = (stratifyIndex + blue) / 5.0; // unbiased threshold
    
    t = clamp(t, 1e-6, 1.0);
    return t;
}

float getSTBNThreshold(DitherInfo d)
{
    uint randomOffset = uint(getObjectHash() * 128 * 128 * 64); // texture resolution 128x128x64
    uint3 texCoord = uint3(d.pixel, d.frameIndex);
    // add random offset
    texCoord.x += randomOffset % 128u;
    texCoord.y += (randomOffset / 128u) % 128u;
    texCoord.z += randomOffset / 16384u;
    // clamp to texture size
    texCoord = texCoord % uint3(128, 128, 64);
    float t = gSpatioTemporalBlueNoiseTex[texCoord];
    return clamp(t, 1e-6, 1.0);
}


/////////////////////////////////////////////////////////////////////////////////////////////
////////////////// DEPRECATED METHODS ///////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////

// WARNING: NOT UP TO DATE (Missing good matrix permutations)
float getPixelDitherThreshold4x4(DitherInfo d)
{
    uint randomOffset = uint(getObjectHash() * 7919);

    uint2 p = d.pixel;
    if (gRotatePattern)
        p = applyRotation(p, d.frameIndex, 4, 4);
    
    // TODO replace lookup with precomputed matrices
    p.x += randomOffset % 4u;
    p.y += randomOffset / 4u;
    p = p % 4u;

    return (ditherMatrix[p.y][p.x] + getTopNoise(d)) / 16.0;
}

