from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_DitherAO():
    g = RenderGraph('DitherRTAO')
    g.create_pass('DitherVBuffer', 'DitherVBuffer', {'useWhitelist': True, 'whitelist': '/root/_materials/Burn,/root/_materials/Fire_Magic,/root/_materials/Healing,/root/_materials/Hit1,/root/_materials/Hit1_001,/root/_materials/Light,/root/_materials/Sadness_water,/root/_materials/Water_drip,/root/_materials/Wirble,/root/_materials/boss_healthbar,/root/_materials/eff_clouds,/root/_materials/effect_Fire,/root/_materials/effect_barrier,/root/_materials/effect_light,/root/_materials/effect_shield,/root/_materials/effect_thunder,Board,CollectInner,Collectible,Smoke,TransparentPlane1,'})
    g.create_pass('ToneMapper', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Linear', 'clamp': False, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('DLSSPass', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.3499999940395355, 'exposure': 0.0})
    g.create_pass('UnpackVBuffer', 'UnpackVBuffer', {})
    g.create_pass('AccumulatePass', 'AccumulatePass', {'enabled': True, 'outputSize': 'Default', 'autoReset': True, 'precisionMode': 'Single', 'maxFrameCount': 0, 'overflowMode': 'Stop'})
    g.create_pass('FSR', 'FSR', {})
    g.create_pass('OutputSwitch', 'Switch', {'count': 4, 'selected': 0, 'i0': 'DLSS', 'i1': 'TAA', 'i2': 'Accumulate', 'i3': 'FSR'})
    g.create_pass('DitherTAA', 'DitherTAA', {'alpha': 0.10000000149011612, 'colorBoxSigma': 1.0})
    g.create_pass('VideoRecorder', 'VideoRecorder', {})
    g.create_pass('PathBenchmark', 'PathBenchmark', {})
    g.create_pass('ParticlePass', 'ParticlePass', {})
    g.create_pass('Ambient', 'ImageEquation', {'formula': 'I0[xy].xxxw', 'format': 'RGBA16Unorm'})
    g.create_pass('Diffuse', 'ImageEquation', {'formula': 'float4(I0[xy].x * I1[xy].xyz, 1.0)', 'format': 'RGBA16Float'})
    g.create_pass('RTAO', 'RTAO', {})
    g.create_pass('NRD', 'NRD', {'enabled': True, 'method': 'ReblurOcclusionDiffuse', 'outputSize': 'Default', 'worldSpaceMotion': False, 'disocclusionThreshold': 2.0, 'maxIntensity': 250.0})
    g.add_edge('DitherVBuffer.mvec', 'DLSSPass.mvec')
    g.add_edge('DitherVBuffer.vbuffer', 'UnpackVBuffer.vbuffer')
    g.add_edge('DitherVBuffer.mvec', 'FSR.mvec')
    g.add_edge('DLSSPass.output', 'OutputSwitch.i0')
    g.add_edge('OutputSwitch.out', 'ToneMapper.src')
    g.add_edge('FSR.output', 'OutputSwitch.i3')
    g.add_edge('AccumulatePass.output', 'OutputSwitch.i2')
    g.add_edge('UnpackVBuffer.rasterZ', 'DLSSPass.depth')
    g.add_edge('UnpackVBuffer.rasterZ', 'FSR.depth')
    g.add_edge('DitherVBuffer.opacity', 'DitherTAA.opacity')
    g.add_edge('DitherVBuffer.mvec', 'DitherTAA.motionVecs')
    g.add_edge('DitherTAA.colorOut', 'OutputSwitch.i1')
    g.add_edge('VideoRecorder', 'DitherVBuffer')
    g.add_edge('ToneMapper', 'PathBenchmark')
    g.add_edge('ParticlePass', 'VideoRecorder')
    g.add_edge('Diffuse.out', 'DLSSPass.color')
    g.add_edge('Diffuse.out', 'AccumulatePass.input')
    g.add_edge('Diffuse.out', 'FSR.color')
    g.add_edge('Diffuse.out', 'DitherTAA.colorIn')
    g.add_edge('DitherVBuffer.color', 'Diffuse.I1')
    g.add_edge('UnpackVBuffer.posW', 'RTAO.wPos')
    g.add_edge('UnpackVBuffer.faceNormalW', 'RTAO.faceNormal')
    g.add_edge('RTAO.ambient', 'NRD.diffuseHitDist')
    g.add_edge('DitherVBuffer.mvec', 'NRD.mvec')
    g.add_edge('UnpackVBuffer.linearZ', 'NRD.viewZ')
    g.add_edge('NRD.filteredDiffuseOcclusion', 'Diffuse.I0')
    g.add_edge('NRD.filteredDiffuseOcclusion', 'Ambient.I0')
    g.add_edge('UnpackVBuffer.normalWRoughnessMaterialID', 'NRD.normWRoughnessMaterialID')
    g.mark_output('ToneMapper.dst')
    g.mark_output('Ambient.out')
    g.mark_output('Diffuse.out')
    return g

DitherAO = render_graph_DitherAO()
try: m.addGraph(DitherAO)
except NameError: None
