from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_GlassTracerRTAO():
    g = RenderGraph('GlassTracerRTAO')
    g.create_pass('GlassTracer', 'GlassTracer', {'useWhitelist': False, 'whitelist': '/root/_materials/Burn,/root/_materials/Fire_Magic,/root/_materials/Healing,/root/_materials/Hit1,/root/_materials/Hit1_001,/root/_materials/Light,/root/_materials/Sadness_water,/root/_materials/Water_drip,/root/_materials/Wirble,/root/_materials/boss_healthbar,/root/_materials/eff_clouds,/root/_materials/effect_Fire,/root/_materials/effect_barrier,/root/_materials/effect_light,/root/_materials/effect_shield,/root/_materials/effect_thunder,Board,CollectInner,Collectible,Smoke,TransparentPlane1,'})
    g.create_pass('ToneMapper', 'ToneMapper', {'outputSize': 'Default', 'outputFormat': 'RGBA32Float', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Linear', 'clamp': False, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('DLSSPass', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.3499999940395355, 'exposure': 0.0})
    g.create_pass('UnpackVBuffer', 'UnpackVBuffer', {})
    g.create_pass('AccumulatePass', 'AccumulatePass', {'enabled': True, 'outputSize': 'Default', 'autoReset': True, 'precisionMode': 'Single', 'maxFrameCount': 0, 'overflowMode': 'Stop'})
    g.create_pass('FSR', 'FSR', {})
    g.create_pass('OutputSwitch', 'Switch', {'count': 6, 'selected': 0, 'i0': 'DLSS', 'i1': 'TAA', 'i2': 'Accumulate', 'i3': 'FSR', 'i4': 'RayReconstruction', 'i5': 'XeSS'})
    g.create_pass('RayReconstructionPass', 'RayReconstructionPass', {})
    g.create_pass('DitherTAA', 'DitherTAA', {'alpha': 0.10000000149011612, 'colorBoxSigma': 1.0})
    g.create_pass('VideoRecorder', 'VideoRecorder', {})
    g.create_pass('PathBenchmark', 'PathBenchmark', {})
    g.create_pass('ParticlePass', 'ParticlePass', {})
    g.create_pass('IntelXeSS', 'IntelXeSS', {})
    g.create_pass('MotionVecVis', 'MotionVecVis', {})
    g.create_pass('RTAO', 'RTAO', {})
    g.create_pass('NRD', 'NRD', {'enabled': True, 'method': 'ReblurOcclusionDiffuse', 'outputSize': 'Default', 'worldSpaceMotion': False, 'disocclusionThreshold': 2.0, 'maxIntensity': 250.0})
    g.create_pass('Ambient', 'ImageEquation', {'formula': 'float4(I0[xy].xxx, 1.0)', 'format': 'RGBA8Unorm'})
    g.create_pass('Diffuse', 'ImageEquation', {'formula': 'float4(I0[xy].x * I1[xy].xyz, I1[xy].w)', 'format': 'RGBA32Float'})
    g.add_edge('GlassTracer.mvec', 'DLSSPass.mvec')
    g.add_edge('GlassTracer.vbuffer', 'UnpackVBuffer.vbuffer')
    g.add_edge('GlassTracer.mvec', 'FSR.mvec')
    g.add_edge('DLSSPass.output', 'OutputSwitch.i0')
    g.add_edge('OutputSwitch.out', 'ToneMapper.src')
    g.add_edge('FSR.output', 'OutputSwitch.i3')
    g.add_edge('AccumulatePass.output', 'OutputSwitch.i2')
    g.add_edge('GlassTracer.mvec', 'RayReconstructionPass.mvec')
    g.add_edge('UnpackVBuffer.linearZ', 'RayReconstructionPass.linearZ')
    g.add_edge('UnpackVBuffer.roughness', 'RayReconstructionPass.roughness')
    g.add_edge('RayReconstructionPass.output', 'OutputSwitch.i4')
    g.add_edge('UnpackVBuffer.diffuse', 'RayReconstructionPass.diffAlbedo')
    g.add_edge('UnpackVBuffer.specular', 'RayReconstructionPass.specAlbedo')
    g.add_edge('UnpackVBuffer.normalV', 'RayReconstructionPass.normal')
    g.add_edge('GlassTracer.mvec', 'DitherTAA.motionVecs')
    g.add_edge('DitherTAA.colorOut', 'OutputSwitch.i1')
    g.add_edge('VideoRecorder', 'GlassTracer')
    g.add_edge('ToneMapper', 'PathBenchmark')
    g.add_edge('ParticlePass', 'VideoRecorder')
    g.add_edge('Diffuse.out', 'DLSSPass.color')
    g.add_edge('Diffuse.out', 'AccumulatePass.input')
    g.add_edge('Diffuse.out', 'FSR.color')
    g.add_edge('Diffuse.out', 'DitherTAA.colorIn')
    g.add_edge('Diffuse.out', 'RayReconstructionPass.color')
    g.add_edge('GlassTracer.mvec', 'IntelXeSS.mvec')
    g.add_edge('Diffuse.out', 'IntelXeSS.color')
    g.add_edge('IntelXeSS.output', 'OutputSwitch.i5')
    g.add_edge('GlassTracer.depth', 'DLSSPass.depth')
    g.add_edge('GlassTracer.depth', 'FSR.depth')
    g.add_edge('GlassTracer.depth', 'IntelXeSS.depth')
    g.add_edge('GlassTracer.mvec', 'MotionVecVis.mvec')
    g.add_edge('UnpackVBuffer.posW', 'MotionVecVis.posW')
    g.add_edge('UnpackVBuffer.posW', 'RTAO.wPos')
    g.add_edge('UnpackVBuffer.faceNormalW', 'RTAO.faceNormal')
    g.add_edge('RTAO.ambient', 'NRD.diffuseHitDist')
    g.add_edge('GlassTracer.depth', 'NRD.viewZ')
    g.add_edge('UnpackVBuffer.normalWRoughnessMaterialID', 'NRD.normWRoughnessMaterialID')
    g.add_edge('GlassTracer.mvec', 'NRD.mvec')
    g.add_edge('NRD.filteredDiffuseOcclusion', 'Ambient.I0')
    g.add_edge('NRD.filteredDiffuseOcclusion', 'Diffuse.I0')
    g.add_edge('GlassTracer.color', 'Diffuse.I1')
    g.mark_output('ToneMapper.dst')
    g.mark_output('MotionVecVis.color')
    g.mark_output('Ambient.out')
    return g

GlassTracerRTAO = render_graph_GlassTracerRTAO()
try: m.addGraph(GlassTracerRTAO)
except NameError: None
