from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_GlassTracer():
    g = RenderGraph('GlassTracer')
    g.create_pass('GlassTracer', 'GlassTracer', {'useWhitelist': True, 'whitelist': '/root/_materials/Burn,/root/_materials/Fire_Magic,/root/_materials/Healing,/root/_materials/Hit1,/root/_materials/Hit1_001,/root/_materials/Light,/root/_materials/Sadness_water,/root/_materials/Water_drip,/root/_materials/Wirble,/root/_materials/boss_healthbar,/root/_materials/eff_clouds,/root/_materials/effect_Fire,/root/_materials/effect_barrier,/root/_materials/effect_light,/root/_materials/effect_shield,/root/_materials/effect_thunder,Board,CollectInner,Collectible,Smoke,TransparentPlane1,'})
    g.create_pass('ToneMapper', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Linear', 'clamp': False, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('DLSSPass', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.3499999940395355, 'exposure': 0.0})
    g.create_pass('UnpackVBuffer', 'UnpackVBuffer', {})
    g.create_pass('AccumulatePass', 'AccumulatePass', {'enabled': True, 'outputSize': 'Default', 'autoReset': True, 'precisionMode': 'Single', 'maxFrameCount': 0, 'overflowMode': 'Stop'})
    g.create_pass('FSR', 'FSR', {})
    g.create_pass('OutputSwitch', 'Switch', {'count': 6, 'selected': 0, 'i0': 'DLSS', 'i1': 'TAA', 'i2': 'Accumulate', 'i3': 'FSR', 'i4': 'RayReconstruction', 'i5': 'XeSS'})
    g.create_pass('RayReconstructionPass', 'RayReconstructionPass', {})
    g.create_pass('DitherTAA', 'DitherTAA', {'alpha': 0.10000000149011612, 'colorBoxSigma': 1.0})
    g.create_pass('VideoRecorder', 'VideoRecorder', {})
    g.create_pass('PathBenchmark', 'PathBenchmark', {})
    g.create_pass('ParticlePass', 'ParticlePass', {})
    g.create_pass('IntelXeSS', 'IntelXeSS', {})
    g.add_edge('GlassTracer.mvec', 'DLSSPass.mvec')
    g.add_edge('GlassTracer.vbuffer', 'UnpackVBuffer.vbuffer')
    g.add_edge('GlassTracer.mvec', 'FSR.mvec')
    g.add_edge('DLSSPass.output', 'OutputSwitch.i0')
    g.add_edge('OutputSwitch.out', 'ToneMapper.src')
    g.add_edge('FSR.output', 'OutputSwitch.i3')
    g.add_edge('AccumulatePass.output', 'OutputSwitch.i2')
    g.add_edge('GlassTracer.mvec', 'RayReconstructionPass.mvec')
    g.add_edge('UnpackVBuffer.linearZ', 'RayReconstructionPass.linearZ')
    g.add_edge('UnpackVBuffer.roughness', 'RayReconstructionPass.roughness')
    g.add_edge('RayReconstructionPass.output', 'OutputSwitch.i4')
    g.add_edge('UnpackVBuffer.diffuse', 'RayReconstructionPass.diffAlbedo')
    g.add_edge('UnpackVBuffer.specular', 'RayReconstructionPass.specAlbedo')
    g.add_edge('UnpackVBuffer.normalV', 'RayReconstructionPass.normal')
    g.add_edge('GlassTracer.mvec', 'DitherTAA.motionVecs')
    g.add_edge('DitherTAA.colorOut', 'OutputSwitch.i1')
    g.add_edge('VideoRecorder', 'GlassTracer')
    g.add_edge('ToneMapper', 'PathBenchmark')
    g.add_edge('ParticlePass', 'VideoRecorder')
    g.add_edge('GlassTracer.color', 'DLSSPass.color')
    g.add_edge('GlassTracer.color', 'AccumulatePass.input')
    g.add_edge('GlassTracer.color', 'FSR.color')
    g.add_edge('GlassTracer.color', 'DitherTAA.colorIn')
    g.add_edge('GlassTracer.color', 'RayReconstructionPass.color')
    g.add_edge('GlassTracer.mvec', 'IntelXeSS.mvec')
    g.add_edge('GlassTracer.color', 'IntelXeSS.color')
    g.add_edge('IntelXeSS.output', 'OutputSwitch.i5')
    g.add_edge('GlassTracer.depth', 'DLSSPass.depth')
    g.add_edge('GlassTracer.depth', 'FSR.depth')
    g.add_edge('GlassTracer.depth', 'IntelXeSS.depth')
    g.mark_output('ToneMapper.dst')
    return g

GlassTracer = render_graph_GlassTracer()
try: m.addGraph(GlassTracer)
except NameError: None
