from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_SMPathTracer_Error():
    g = RenderGraph('SMPathTracer_Error')
    g.create_pass('FLIPPass', 'FLIPPass', {'enabled': True, 'useMagma': True, 'clampInput': False, 'isHDR': False, 'toneMapper': 'ACES', 'useCustomExposureParameters': False, 'startExposure': 0.0, 'stopExposure': 0.0, 'numExposures': 2, 'monitorWidthPixels': 3840, 'monitorWidthMeters': 0.699999988079071, 'monitorDistanceMeters': 0.699999988079071, 'computePooledFLIPValues': False, 'useRealMonitorInfo': False})
    g.create_pass('ToneMapper', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Linear', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('VBufferRT', 'VBufferRT', {'outputSize': 'Default', 'samplePattern': 'Stratified', 'sampleCount': 32, 'useAlphaTest': True, 'adjustShadingNormals': True, 'forceCullMode': False, 'cull': 'Back', 'useTraceRayInline': False, 'useDOF': True})
    g.create_pass('TestPathSM', 'TestPathSM', {'maxBounces': 10, 'computeDirect': True, 'useImportanceSampling': True, 'shadowTracingMode': 'LeakTracing'})
    g.create_pass('AccumulatePass', 'AccumulatePass', {'enabled': True, 'outputSize': 'Default', 'autoReset': True, 'precisionMode': 'Double', 'maxFrameCount': 10000, 'overflowMode': 'Stop'})
    g.create_pass('ErrorMeasurePass', 'ErrorMeasurePass', {'ReferenceImagePath': '', 'MeasurementsFilePath': '', 'IgnoreBackground': True, 'ComputeSquaredDifference': True, 'ComputeAverage': False, 'UseLoadedReference': False, 'ReportRunningError': True, 'RunningErrorSigma': 0.9950000047683716, 'SelectedOutputId': 'Difference', 'EnablePerFrameError': False})
    g.create_pass('Ref_TestPathSM', 'TestPathSM', {'maxBounces': 10, 'computeDirect': True, 'useImportanceSampling': True, 'shadowTracingMode': 'RayShadows'})
    g.create_pass('Ref_AccumulatePass', 'AccumulatePass', {'enabled': True, 'outputSize': 'Default', 'autoReset': True, 'precisionMode': 'Double', 'maxFrameCount': 10000, 'overflowMode': 'Stop'})
    g.create_pass('Ref_ToneMapper', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Linear', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('ErrorOverlay', 'ErrorOverlay', {'ImageMode0': 'Image', 'ImageMode1': 'Reference', 'ImageMode2': 'None', 'ImageMode3': 'FLIP', 'LineThickness': 1, 'LineColor': [1.0, 1.0, 1.0]})
    g.add_edge('VBufferRT.vbuffer', 'TestPathSM.vbuffer')
    g.add_edge('VBufferRT.viewW', 'TestPathSM.viewW')
    g.add_edge('TestPathSM.color', 'AccumulatePass.input')
    g.add_edge('VBufferRT.vbuffer', 'Ref_TestPathSM.vbuffer')
    g.add_edge('VBufferRT.viewW', 'Ref_TestPathSM.viewW')
    g.add_edge('Ref_TestPathSM.color', 'Ref_AccumulatePass.input')
    g.add_edge('AccumulatePass.output', 'ErrorMeasurePass.Source')
    g.add_edge('Ref_AccumulatePass.output', 'ErrorMeasurePass.Reference')
    g.add_edge('AccumulatePass.output', 'ToneMapper.src')
    g.add_edge('Ref_AccumulatePass.output', 'Ref_ToneMapper.src')
    g.add_edge('Ref_ToneMapper.dst', 'FLIPPass.testImage')
    g.add_edge('ToneMapper.dst', 'FLIPPass.referenceImage')
    g.add_edge('FLIPPass.errorMapDisplay', 'ErrorOverlay.FLIP')
    g.add_edge('ErrorMeasurePass.Output', 'ErrorOverlay.MSE')
    g.add_edge('ToneMapper.dst', 'ErrorOverlay.Image')
    g.add_edge('Ref_ToneMapper.dst', 'ErrorOverlay.Reference')
    g.add_edge('TestPathSM', 'Ref_TestPathSM')
    g.add_edge('Ref_TestPathSM', 'AccumulatePass')
    g.add_edge('AccumulatePass', 'Ref_AccumulatePass')
    g.add_edge('Ref_AccumulatePass', 'ToneMapper')
    g.add_edge('ToneMapper', 'Ref_ToneMapper')
    g.mark_output('ErrorOverlay.output')
    return g

SMPathTracer_Error = render_graph_SMPathTracer_Error()
try: m.addGraph(SMPathTracer_Error)
except NameError: None
